<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class ThrottleRequests extends \Illuminate\Routing\Middleware\ThrottleRequests
{

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse)  $next
     * @return \Illuminate\Http\Response|\Illuminate\Http\RedirectResponse
     */
    protected function buildResponse($key, $maxAttempts)
    {
        return parent::buildResponse($key, $maxAttempts); // TODO: Change the autogenerated stub
    }
}

// <?php

// namespace App\Http\Middleware;

// use Closure;

// class ThrottleRequests extends \Illuminate\Routing\Middleware\ThrottleRequests
// {
//     protected function buildResponse($key, $maxAttempts)
//     {
//         return parent::buildResponse($key, $maxAttempts); // TODO: Change the autogenerated stub
//     }
// }